### ISSUE TITLE
항목 이름 변경 요청

### ISSUE THREAD

**Issue by coffeetea99** [integraldx/HowToSNUCSE#21]
<기초 지식>이라는 것에 너무 모호하고 광범위합니다. <기초 지식>에 현재 작성되어 있는 항목들이 네트워크 관련 항목들이므로 <네트워크 기초 용어>로 항목 이름을 변경하는 것을 요청하고, 다른 기초적인 지식을 적어 놓을 경우에도 분류해서 적는 것이 좋을 것 같습니다.
<컴퓨터 사용> 항목의 이름을 <OS별 기초 지식>으로 바꾸는 것을 요청합니다.

**Comment by coffeetea99** [comment]
더불어, 최상위 페이지의 [분류]에 속한 항목의 수는 굳이 적게 유지할 필요가 없어 보입니다.

**Comment by gratus907** [comment]
네트워크 외의 다른 내용에 대해 적게 될 때 이를 다시 논의할 필요는 있어 보입니다. 결국은 최상위 페이지 분류가 많은 것과 <기초 지식> 아래 분류가 많은 것 중 무엇이 나은지의 문제라서...
일단 저는 @coffeetea99 님의 의견에 대체로 동의합니다. 다만 가독성을 위해서라도 항목을 적절히 나누는 것에 대해서는 더 많은 토론이 필요해 보입니다.

**Comment by coffeetea99** [comment]
<컴퓨터 사용> 항목에 각 운영 체제별로 하위 항목이 생성되어 있는데, 이 하위 내용이 방대해지면 최상위 항목에 [윈도우], [리눅스], [맥OS]를 두는 방식도 좋아 보입니다.

**Comment by integraldx** [comment]
2020.02.01 @coffeetea99 와 @integraldx 의 회의에서 항목의 이름을 변경하는 것으로 결정되었습니다. 이슈는 닫겠습니다.
