### ISSUE TITLE
프로그래밍 언어 작성 템플릿

### ISSUE THREAD

**Issue by integraldx** [integraldx/HowToSNUCSE#5]
프로그래밍 언어 항목의 내용들을 작성하기 위한 기본적인 템플릿이 필요합니다

**Comment by finalchild** [comment]
프로그래밍 언어 문서는 매우 간략하게부터 언어 튜토리얼까지 다양한 분량으로 쓸 수 있을텐데, 어떤 글을 목적으로 해야 할까요?
스누씨 대상이니 어느 과목에서 어떤 언어를 사용하는지도 정리되어 있으면 좋을 것 같습니다.

**Comment by integraldx** [comment]
c-language 브랜치가 만들어졌습니다
