### ISSUE TITLE
IDE, 텍스트 에디터 작성 템플릿

### ISSUE THREAD

**Issue by integraldx** [integraldx/HowToSNUCSE#6]
#5 와 마찬가지로, IDE와 텍스트 에디터에 대한 내용을 작성하기 위한 템플릿이 필요합니다.

**Comment by nevivurn** [comment]
- 이름
- 설치 절차 / 기본 setup
- 장단점
- 기타 HOWTO / Notes

정도 있으면 충분할까요?

**Comment by gratus907** [comment]
Maybe some recommendations? Useful plugins or sth like those...

**Comment by integraldx** [comment]
[editor-vscode](https://github.com/integraldx/HowToSNUCSE/tree/editor-vscode) 브랜치에서 템플릿 완성에 대한 논의도 겸하고 싶습니다. 이 브랜치가 머지되면 머지된 내용에 따라 템플릿을 만드는 것으로 해도 될까요?

**Comment by integraldx** [comment]
#10 풀리퀘가 만들어졌습니다.
